apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: gh-tekton-quay-go-ujyfrrtk 
  janus-idp.io/tekton: gh-tekton-quay-go-ujyfrrtk
  backstage.io/kubernetes-id: gh-tekton-quay-go-ujyfrrtk
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gh-tekton-quay-go-ujyfrrtk
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml